# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box
  config.vm.box = "ubuntu/xenial64"
  #config.vm.hostname = "refbox"

  # Bump up the specs a bit
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  # Do some basic provisioning
  config.vm.provision "shell", path: "../scripts/debian/upgrade.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/essentials.sh"
  config.vm.provision "shell", path: "../scripts/common/vim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/zsh.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"

end
