# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box.
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ctfbox"

  # Configure SSH access.
  config.ssh.username = "vagrant"

  # Forward ports. Modify as needed.
  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "forwarded_port", guest: 24242, host: 24242

  # Bump up the specs a bit
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

  # The following line prevents easy VM -> Host privesc through /vagrant/Vagrantfile.
  # This does, however, only prevents unprivileged users from doing so as root in the
  # VM can still `mount -o remount,rw`.
  # If you are going to run untrusted code you should instead uncomment the second
  # line to disable the /vagrant directory alltogether (or maybe not use vagrant at all).
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["ro"], owner: "root", group: "root"
  #config.vm.synced_folder ".", "/vagrant", disabled: true

  # Share CTF folder
  config.vm.synced_folder "~/Desktop/ctf", "/home/vagrant/ctf"

  # Do some basic provisioning.
  config.vm.provision "shell", path: "../scripts/debian/upgrade.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/essentials_legacy.sh"
  config.vm.provision "shell", path: "../scripts/common/vim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/zsh.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/multiarch.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/netsec.sh"
  config.vm.provision "shell", path: "../scripts/packages/virtualenv.sh", privileged: false

  # Install CTF related packages.
  config.vm.provision "shell", path: "../scripts/packages/capstone.sh", privileged: false
  #config.vm.provision "shell", path: "../scripts/packages/keystone.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/unicorn.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/gef.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/ropgadget.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/checksec.sh", privileged: false
end
