# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box.
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ctfbox"

  # Configure SSH access.
  config.ssh.username = "vagrant"

  # Forward ports. Modify as needed.
  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "forwarded_port", guest: 24242, host: 24242

  # Bump up the specs a bit
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  # Share CTF folder
  # config.vm.synced_folder "~/Desktop/ctf", "/home/vagrant/ctf"

  # Do some basic provisioning.
  config.vm.provision "shell", path: "../scripts/debian/upgrade.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/essentials.sh"
  config.vm.provision "shell", path: "../scripts/common/vim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/zsh.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/debian/lockdown.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/multiarch.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/netsec.sh"
  config.vm.provision "shell", path: "../scripts/packages/virtualenv.sh"

  # Install CTF related packages.
  config.vm.provision "shell", path: "../scripts/packages/capstone.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/pwndbg.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/pin.sh", privileged: false
  # config.vm.provision "shell", path: "../scripts/packages/z3.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/ropgadget.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/pwntools.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/checksec.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/angr.sh", privileged: false

  # Uninstall unneeded packages
  config.vm.provision "shell", path: "../scripts/debian/autoremove.sh"

end
