# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box.
  config.vm.box = "ubuntu/zesty64"
  config.vm.hostname = "manticore"

  # Forward ports. Modify as needed.
  #config.vm.network "forwarded_port", guest: 4444, host: 4444

  # Bump up the specs a bit
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  # Provisioning
  config.vm.provision "shell", path: "../scripts/debian/upgrade.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/essentials.sh"

  config.vm.provision "shell", path: "../scripts/common/vim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/zsh.sh", privileged: false

  config.vm.provision "shell", path: "../scripts/ubuntu/multiarch.sh"

  config.vm.provision "shell", path: "../scripts/packages/gef.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/manticore.sh", privileged: false

  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"
end
